### ISSUE TITLE
大佬,能教下怎么用腾讯云函数嘛

### ISSUE THREAD

**Issue by simple201** [DoveBoy/jd_scripts-gitee#6]
十分抱歉打扰了,不知道能不能教一下

**Comment by DoveBoy** [comment]
repo里面关于云函数的教程写的很详细了，自己找吧

**Comment by simple201** [comment]
4.2 工具部署

下载 Serverless 工具，快速部署函数
这步没懂,去哪里下载serverless工具呀？

**Comment by DoveBoy** [comment]
@simple201 善用搜索，此类基础问题不予解答

**Comment by simple201** [comment]
> @simple201 善用搜索，此类基础问题不予解答

部署命令输入后提示这个,Serverless » secretKey is required,谷歌百度都搜了,也没结果

**Comment by DoveBoy** [comment]
@simple201 `secretKey`、`SecretId`未提供

**Comment by simple201** [comment]
> repo里面关于云函数的教程写的很详细了，自己找吧
在腾讯云函数里面申请了secretKey、SecretId,不知道怎么用, serverless deploy添加到这个部署代码里面嘛？
